theCommunityProject/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # 아티클 홈/정렬
    path('', views.home, name='home'),

    # 상세 보기
    path('<int:article_id>/', views.detail, name='detail'),

    # 좋아요, 스크랩
    path('<int:article_id>/like/', views.article_like, name='article_like'),
    path('<int:article_id>/scrap/', views.article_scrap, name='article_scrap'),

    # 댓글 CRUD + 좋아요
    path('<int:article_id>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comment/<int:comment_id>/update/', views.comment_update, name='comment_update'),
    path('<int:article_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_id>/comment/<int:comment_id>/like/', views.comment_like, name='comment_like'),

    # 답글 CRUD + 좋아요
    path('<int:article_id>/comment/<int:comment_id>/reply/create/', views.reply_create, name='reply_create'),
    path('<int:article_id>/comment/<int:comment_id>/reply/<int:reply_id>/update/', views.reply_update, name='reply_update'),
    path('<int:article_id>/comment/<int:comment_id>/reply/<int:reply_id>/delete/', views.reply_delete, name='reply_delete'),
    path('<int:article_id>/comment/<int:comment_id>/reply/<int:reply_id>/like/', views.reply_like, name='reply_like'),

    # ai 추가
    path('<int:post_id>/comment/evidence/', views.detail_comment_ai_response, name='detail_comment_ai_response'),
    path('<int:post_id>/detail/comment/<int:comment_id>/reply/evidence/', views.detail_reply_ai_response, name='detail_reply_ai_response'),
]

theCommunityProject/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('', views.home, name='home'), #메인 페이지 변경
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('proposals/', include('proposals.urls')),
    path('articles/', include('articles.urls')),
    path('scraps/', include('scraps.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theCommunityProject/proposals/urls.py
from django.urls import path
from . import views

app_name = 'proposals'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/like/', views.detail_post_like, name='detail_post_like'),
    path('<int:post_id>/scrap/', views.detail_post_scrap, name='detail_post_scrap'),
    path('<int:post_id>/comment/create/', views.detail_comment_create, name='detail_comment_create'),
    path('<int:post_id>/comment/<int:comment_id>/update/', views.detail_comment_update, name='detail_comment_update'),
    path('<int:post_id>/comment/<int:comment_id>/delete/', views.detail_comment_delete, name='detail_comment_delete'),
    path('<int:post_id>/comment/<int:comment_id>/like/', views.detail_comment_like, name='detail_comment_like'),
    path('<int:post_id>/comment/<int:comment_id>/link/', views.detail_comment_link, name='detail_comment_link'),
    path('<int:post_id>/comment/<int:comment_id>/reply/create/', views.detail_reply_create, name='detail_reply_create'),
    path('<int:post_id>/comment/<int:comment_id>/reply/<int:reply_id>/update/', views.detail_reply_update, name='detail_reply_update'),
    path('<int:post_id>/comment/<int:comment_id>/reply/<int:reply_id>/delete/', views.detail_reply_delete, name='detail_reply_delete'),
    path('<int:post_id>/comment/<int:comment_id>/reply/<int:reply_id>/like', views.detail_reply_like, name='detail_reply_like'),
    path('<int:post_id>/detail/comment/<int:comment_id>/reply/evidence/', views.detail_reply_ai_response, name='detail_reply_ai_response'),
]

theCommunityProject/scraps/urls.py
from django.urls import path
from scraps import views

app_name = "scraps"

urlpatterns = [
    path('article/', views.scraps_article, name='scraps_article'),
    path('community/', views.scraps_community, name='scraps_community'),
    path('proposal/', views.scraps_proposal, name='scraps_proposal'),
]

theCommunityProject/scraps/models.py
from django.db import models

# Create your models here.

theCommunityProject/scraps/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
@login_required(login_url='accounts/login')
def scraps_article(request):
    """
    아티클 스크랩
    """
    article_posts = request.user.scrapped_article_posts.all()
    context = {
        'article_posts': article_posts,
    }

    return render(request, 'scrapped_article.html', context)

@login_required(login_url='accounts/login')
def scraps_community(request):
    """
    커뮤니티 스크랩
    """
    community_posts = request.user.scrapped_community_posts.all()
    context = {
        'community_posts': community_posts,
    }

    return render(request, 'scrapped_community.html', context)

@login_required(login_url='accounts/login')
def scraps_proposal(request):
    """
    정책 제안 스크랩
    """
    proposal_posts = request.user.scrapped_proposal_posts.all()
    context = {
        'proposal_posts': proposal_posts,
    }

    return  render(request, 'scrapped_proposal.html', context)

theCommunityProject/scraps/templates/scrapped_article.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>스크랩 - 더 커뮤니티</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/scrap.css' %}">
      <script src="{% static 'js/scrap.js' %}"></script>
  </head>
  <body>
    <div id="header"></div>
    <div class="container">
      <h4>스크랩</h4>
      <div class="tabs">
        <a href="{% url 'scraps:scraps_article' %}" class="article-nav active"
          >아티클</a
        >
        <a href="{% url 'scraps:scraps_community' %}" class="community-nav"
          >커뮤니티</a
        >
        <a href="{% url 'scraps:scraps_proposal' %}" class="policy-nav"
          >정책 제안</a
        >
      </div>

      {% for post in article_posts %}
      <a href="{% url 'articles:detail' post.id %}" class="card-link">
      <div class="post">
        <div class="post-info">
          <div class="post-meta">{{ post.created_at|date:"Y.m.d" }}</div>
          <div class="post-title">{{ post.title }}</div>
          <div class="post-content">{{ post.content|truncatechars:70 }}</div>
          <div class="comment-div4">
            <div class="comment-buttons2 like">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                viewBox="0 0 20 20"
                fill="none"
              >
                <mask
                  id="mask0_1422_15530"
                  style="mask-type: alpha"
                  maskUnits="userSpaceOnUse"
                  x="0"
                  y="0"
                  width="20"
                  height="20"
                >
                  <rect width="20" height="20" fill="#D9D9D9" />
                </mask>
                <g mask="url(#mask0_1422_15530)">
                  <path
                    d="M16.5895 7.16631C16.9721 7.16631 17.31 7.31304 17.6033 7.60649C17.8968 7.89982 18.0435 8.23778 18.0435 8.62039V9.91964C18.0435 10.0041 18.0327 10.0946 18.011 10.1911C17.9894 10.2875 17.9652 10.3775 17.9384 10.4612L15.6331 15.9007C15.5179 16.1579 15.3247 16.3752 15.0535 16.5526C14.7823 16.73 14.4993 16.8187 14.2045 16.8187H5.74605V7.16631L10.4252 2.52735C10.5852 2.36755 10.7703 2.27217 10.9806 2.2412C11.191 2.21023 11.3925 2.24629 11.5853 2.34939C11.7782 2.45261 11.9195 2.59907 12.0092 2.78877C12.0989 2.97846 12.118 3.17493 12.0665 3.37816L11.2002 7.16631H16.5895ZM6.95259 7.67989V15.6121H14.2073C14.264 15.6121 14.322 15.5966 14.3813 15.5657C14.4407 15.5347 14.4858 15.4831 14.5168 15.411L16.837 9.98157V8.62039C16.837 8.54813 16.8138 8.48881 16.7674 8.44243C16.721 8.39604 16.6617 8.37285 16.5895 8.37285H9.67516L10.6836 3.96434L6.95259 7.67989ZM3.41038 16.8187C3.01048 16.8187 2.66816 16.6763 2.38341 16.3915C2.09867 16.1068 1.9563 15.7645 1.9563 15.3646V8.62039C1.9563 8.22049 2.09867 7.87817 2.38341 7.59342C2.66816 7.30868 3.01048 7.16631 3.41038 7.16631H5.74605V8.37285H3.41038C3.33813 8.37285 3.2788 8.39604 3.23242 8.44243C3.18603 8.48881 3.16284 8.54813 3.16284 8.62039V15.3646C3.16284 15.4368 3.18603 15.4961 3.23242 15.5425C3.2788 15.5889 3.33813 15.6121 3.41038 15.6121H5.74605V16.8187H3.41038Z"
                    fill="#A3A3A3"
                  />
                </g>
              </svg>
              <div class="comment-div3">{{ post.liked.count }}</div>
            </div>
            <div class="comment-div4">
              <div class="comment-buttons2 messages">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                >
                  <mask
                    id="mask0_374_11829"
                    style="mask-type: alpha"
                    maskUnits="userSpaceOnUse"
                    x="0"
                    y="0"
                    width="24"
                    height="24"
                  >
                    <rect width="24" height="24" fill="#D9D9D9" />
                  </mask>
                  <g mask="url(#mask0_374_11829)">
                    <path
                      d="M6.44068 17.9315L4.57373 19.7983C4.30842 20.0637 4.00324 20.1239 3.6582 19.9787C3.31331 19.8334 3.14087 19.5718 3.14087 19.194V5.62917C3.14087 5.15808 3.30406 4.75934 3.63046 4.43295C3.95685 4.10655 4.35559 3.94336 4.82668 3.94336H19.1734C19.6445 3.94336 20.0433 4.10655 20.3697 4.43295C20.696 4.75934 20.8592 5.15808 20.8592 5.62917V16.2457C20.8592 16.7168 20.696 17.1156 20.3697 17.442C20.0433 17.7684 19.6445 17.9315 19.1734 17.9315H6.44068ZM5.84525 16.5327H19.1734C19.2452 16.5327 19.311 16.5028 19.3707 16.443C19.4305 16.3833 19.4604 16.3175 19.4604 16.2457V5.62917C19.4604 5.55736 19.4305 5.49162 19.3707 5.43194C19.311 5.3721 19.2452 5.34218 19.1734 5.34218H4.82668C4.75487 5.34218 4.68913 5.3721 4.62945 5.43194C4.56961 5.49162 4.53969 5.55736 4.53969 5.62917V17.8241L5.84525 16.5327Z"
                      fill="white"
                    />
                  </g>
                </svg>
                <div class="comment-div3">{{ post.article_comments.count }}</div>
              </div>
            </div>
          </div>
        </div>
        <img
          class="post-thumnail"
          src="{{post.image.url}}"
          alt="{{post.thumnail}}"
        />
      </div>
      {% empty %}
      <div class="none-post">
        <div class="none-post-info">스크랩 된 아티클이 없습니다.</div>
        <div class="goTo">
          <a href="{% url 'articles:home' %}" style="color: #fff"
            >아티클 보러가기</a
          >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="21"
            height="20"
            viewBox="0 0 21 20"
            fill="none"
          >
            <mask
              id="mask0_1422_8232"
              style="mask-type: alpha"
              maskUnits="userSpaceOnUse"
              x="0"
              y="0"
              width="21"
              height="20"
            >
              <rect x="0.5" width="20" height="20" fill="#D9D9D9" />
            </mask>
            <g mask="url(#mask0_1422_8232)">
              <path
                d="M14.5721 6.87138L6.20565 15.2293C6.08149 15.3534 5.9255 15.4139 5.73769 15.4111C5.54973 15.4083 5.39367 15.3448 5.26951 15.2206C5.1455 15.0964 5.0835 14.9419 5.0835 14.7569C5.0835 14.5719 5.1455 14.4174 5.26951 14.2932L13.6275 5.92673H6.27983C6.08933 5.92673 5.92961 5.86226 5.80067 5.73332C5.67188 5.60438 5.60748 5.44465 5.60748 5.25416C5.60748 5.06351 5.67188 4.90386 5.80067 4.77522C5.92961 4.64643 6.08933 4.58203 6.27983 4.58203H15.1064C15.3361 4.58203 15.5285 4.65965 15.6837 4.81489C15.8391 4.97028 15.9168 5.16272 15.9168 5.39221V14.219C15.9168 14.4095 15.8524 14.5692 15.7234 14.698C15.5945 14.8269 15.4348 14.8914 15.2443 14.8914C15.0536 14.8914 14.8939 14.8269 14.7651 14.698C14.6365 14.5692 14.5721 14.4095 14.5721 14.219V6.87138Z"
                fill="white"
              />
            </g>
          </svg>
        </div>
      </div>
      {% endfor %}
    </div>
    <div id="footer"></div>
    <script src="./scrap.js"></script>
  </body>
</html>

theCommunityProject/scraps/templates/scrapped_proposal.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>스크랩 - 더 커뮤니티</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/scrap.css' %}">
      <script src="{% static 'js/scrap.js' %}"></script>
  </head>
  <body>
    <div id="header"></div>

    <div class="container">
      <h4>스크랩</h4>
      <div class="tabs">
        <a href="{% url 'scraps:scraps_article' %}" class="article-nav"
          >아티클</a
        >
        <a href="{% url 'scraps:scraps_community' %}" class="community-nav"
          >커뮤니티</a
        >
        <a href="{% url 'scraps:scraps_proposal' %}" class="policy-nav active"
          >정책 제안</a
        >
      </div>

      <div class="proposal_grid">
        {% for post in proposal_posts %}
        <a href="{% url 'proposals:detail' post.id %}" class="card-link">
          <div class="article-card">
            {% if post.result_number == 1 %}
            <img
              src="{% static 'thumbnail/agree.png' %}"
              class="thumnail"
            />
            {% elif post.result_number == 2 %}
            <img
              src="{% static 'thumbnail/disagree.png' %}"
              class="thumnail"
            />
            {% else %}
            <img
              src="{% static 'thumbnail/neutral.png' %}"
              class="thumnail"
            />
            {% endif %}
            <div class="article-card-contents">
              <div class="article-card-contents-div1">
                {{ post.title|truncatechars:40 }}
              </div>
              <div class="comment-div4">
                <div class="comment-buttons2 like">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="20"
                    height="20"
                    viewBox="0 0 20 20"
                    fill="none"
                  >
                    <mask
                      id="mask0_1422_15530"
                      style="mask-type: alpha"
                      maskUnits="userSpaceOnUse"
                      x="0"
                      y="0"
                      width="20"
                      height="20"
                    >
                      <rect width="20" height="20" fill="#D9D9D9" />
                    </mask>
                    <g mask="url(#mask0_1422_15530)">
                      <path
                        d="M16.5895 7.16631C16.9721 7.16631 17.31 7.31304 17.6033 7.60649C17.8968 7.89982 18.0435 8.23778 18.0435 8.62039V9.91964C18.0435 10.0041 18.0327 10.0946 18.011 10.1911C17.9894 10.2875 17.9652 10.3775 17.9384 10.4612L15.6331 15.9007C15.5179 16.1579 15.3247 16.3752 15.0535 16.5526C14.7823 16.73 14.4993 16.8187 14.2045 16.8187H5.74605V7.16631L10.4252 2.52735C10.5852 2.36755 10.7703 2.27217 10.9806 2.2412C11.191 2.21023 11.3925 2.24629 11.5853 2.34939C11.7782 2.45261 11.9195 2.59907 12.0092 2.78877C12.0989 2.97846 12.118 3.17493 12.0665 3.37816L11.2002 7.16631H16.5895ZM6.95259 7.67989V15.6121H14.2073C14.264 15.6121 14.322 15.5966 14.3813 15.5657C14.4407 15.5347 14.4858 15.4831 14.5168 15.411L16.837 9.98157V8.62039C16.837 8.54813 16.8138 8.48881 16.7674 8.44243C16.721 8.39604 16.6617 8.37285 16.5895 8.37285H9.67516L10.6836 3.96434L6.95259 7.67989ZM3.41038 16.8187C3.01048 16.8187 2.66816 16.6763 2.38341 16.3915C2.09867 16.1068 1.9563 15.7645 1.9563 15.3646V8.62039C1.9563 8.22049 2.09867 7.87817 2.38341 7.59342C2.66816 7.30868 3.01048 7.16631 3.41038 7.16631H5.74605V8.37285H3.41038C3.33813 8.37285 3.2788 8.39604 3.23242 8.44243C3.18603 8.48881 3.16284 8.54813 3.16284 8.62039V15.3646C3.16284 15.4368 3.18603 15.4961 3.23242 15.5425C3.2788 15.5889 3.33813 15.6121 3.41038 15.6121H5.74605V16.8187H3.41038Z"
                        fill="#A3A3A3"
                      />
                    </g>
                  </svg>
                  <div class="comment-div3">{{ post.liked.count }}</div>
                </div>
                <div class="comment-div4">
                  <div class="comment-buttons2 messages">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="24"
                      height="24"
                      viewBox="0 0 24 24"
                      fill="none"
                    >
                      <mask
                        id="mask0_374_11829"
                        style="mask-type: alpha"
                        maskUnits="userSpaceOnUse"
                        x="0"
                        y="0"
                        width="24"
                        height="24"
                      >
                        <rect width="24" height="24" fill="#D9D9D9" />
                      </mask>
                      <g mask="url(#mask0_374_11829)">
                        <path
                          d="M6.44068 17.9315L4.57373 19.7983C4.30842 20.0637 4.00324 20.1239 3.6582 19.9787C3.31331 19.8334 3.14087 19.5718 3.14087 19.194V5.62917C3.14087 5.15808 3.30406 4.75934 3.63046 4.43295C3.95685 4.10655 4.35559 3.94336 4.82668 3.94336H19.1734C19.6445 3.94336 20.0433 4.10655 20.3697 4.43295C20.696 4.75934 20.8592 5.15808 20.8592 5.62917V16.2457C20.8592 16.7168 20.696 17.1156 20.3697 17.442C20.0433 17.7684 19.6445 17.9315 19.1734 17.9315H6.44068ZM5.84525 16.5327H19.1734C19.2452 16.5327 19.311 16.5028 19.3707 16.443C19.4305 16.3833 19.4604 16.3175 19.4604 16.2457V5.62917C19.4604 5.55736 19.4305 5.49162 19.3707 5.43194C19.311 5.3721 19.2452 5.34218 19.1734 5.34218H4.82668C4.75487 5.34218 4.68913 5.3721 4.62945 5.43194C4.56961 5.49162 4.53969 5.55736 4.53969 5.62917V17.8241L5.84525 16.5327Z"
                          fill="white"
                        />
                      </g>
                    </svg>
                    <div class="comment-div3">
                      {{ post.proposal_comments.count }}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </a>
        {% empty %}
        <div class="none-post">
          <div class="none-post-info">스크랩 된 정책제안이 없습니다.</div>
          <div class="goTo" style="width: 10.81rem">
            <a href="{% url 'proposals:home' %}" style="color: #fff; width: 11rem"
              >정책제안 보러가기</a
            >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="21"
              height="20"
              viewBox="0 0 21 20"
              fill="none"
            >
              <mask
                id="mask0_1422_8232"
                style="mask-type: alpha"
                maskUnits="userSpaceOnUse"
                x="0"
                y="0"
                width="21"
                height="20"
              >
                <rect x="0.5" width="20" height="20" fill="#D9D9D9" />
              </mask>
              <g mask="url(#mask0_1422_8232)">
                <path
                  d="M14.5721 6.87138L6.20565 15.2293C6.08149 15.3534 5.9255 15.4139 5.73769 15.4111C5.54973 15.4083 5.39367 15.3448 5.26951 15.2206C5.1455 15.0964 5.0835 14.9419 5.0835 14.7569C5.0835 14.5719 5.1455 14.4174 5.26951 14.2932L13.6275 5.92673H6.27983C6.08933 5.92673 5.92961 5.86226 5.80067 5.73332C5.67188 5.60438 5.60748 5.44465 5.60748 5.25416C5.60748 5.06351 5.67188 4.90386 5.80067 4.77522C5.92961 4.64643 6.08933 4.58203 6.27983 4.58203H15.1064C15.3361 4.58203 15.5285 4.65965 15.6837 4.81489C15.8391 4.97028 15.9168 5.16272 15.9168 5.39221V14.219C15.9168 14.4095 15.8524 14.5692 15.7234 14.698C15.5945 14.8269 15.4348 14.8914 15.2443 14.8914C15.0536 14.8914 14.8939 14.8269 14.7651 14.698C14.6365 14.5692 14.5721 14.4095 14.5721 14.219V6.87138Z"
                  fill="white"
                />
              </g>
            </svg>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div id="footer"></div>
    <script src="./scrap.js"></script>
  </body>
</html>